"""empty message

Revision ID: 287d008c7349
Revises: 4ef2e9974cd0
Create Date: 2023-03-31 12:42:36.308150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287d008c7349'
down_revision = '4ef2e9974cd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('car_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_table('car_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('ppd', sa.Integer(), nullable=False),
    sa.Column('min_rent', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('deposit', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['car_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['car_companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['car_models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id')
    )
    op.create_table('rented',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('carID', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('booking_time', sa.DateTime(), nullable=False),
    sa.Column('rented_from', sa.DateTime(), nullable=False),
    sa.Column('rented_till', sa.DateTime(), nullable=False),
    sa.Column('car_taken', sa.Boolean(), nullable=True),
    sa.Column('car_delivery', sa.Boolean(), nullable=True),
    sa.Column('city_taken_id', sa.Integer(), nullable=True),
    sa.Column('city_delivery_id', sa.Integer(), nullable=True),
    sa.Column('final_status', sa.String(length=30), nullable=True),
    sa.Column('said_date', sa.Boolean(), nullable=True),
    sa.Column('said_time', sa.Boolean(), nullable=True),
    sa.Column('proper_condition', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('fine', sa.Integer(), nullable=True),
    sa.Column('fine_paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['carID'], ['cars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['city_delivery_id'], ['cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['city_taken_id'], ['cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('temporary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('booking_time', sa.DateTime(), nullable=False),
    sa.Column('rent_from', sa.DateTime(), nullable=False),
    sa.Column('rent_till', sa.DateTime(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temporary')
    op.drop_table('rented')
    op.drop_table('cars')
    op.drop_table('car_models')
    op.drop_table('car_companies')
    op.drop_table('car_categories')
    # ### end Alembic commands ###
